### ISSUE TITLE
Next version TODO

### ISSUE THREAD

**Issue by bertob** [bertob/bertob.github.io#2]
- [ ] More up to date GNOME laptop screenshot
- [ ] Add Post-Collapse Computing talk
- [ ] Add GNOME Software revamp?
- [ ] New social media image
